let actionTypes = {
    SIGNIN: "SIGNIN",
    SIGNOUT: "SIGNOUT",

    SIGNIN_LOADER_OPEN: "SIGNIN_LOADER_OPEN",
    SIGNIN_LOADER_CLOSE: "SIGNIN_LOADER_CLOSE",


    POSTJOB: "POSTJOB",
    POSTEDJOBS:"POSTEDJOBS",

    GETSTUDENTS: "GETSTUDENTS",
    GETCOMPANIES: "GETCOMPANIES",
    GETCOMPANIESONLY:"GETCOMPANIESONLY",

    REQUEST: "REQUEST",
    REQUESTED_DATA: "REQUESTED_DATA",
    UPDATED: "UPDATED"
}
export default actionTypes